FROM python:3.10-slim

WORKDIR /usr/app/src

# For testing, we map source code directly to /usr/app/src
# (in the volume mapping)

# Then, copy the requirements manually
COPY requirements.txt .
RUN pip install -r requirements.txt

CMD [ "python", "-u", "./server.py", "--debug", "yes"]